source 'https://rubygems.org'

gem 'apotomo'
gem 'coffee-rails', '~> 4.0.0'
gem 'execjs'
gem 'haml'
gem 'haml_coffee_assets'
gem 'joosy', github: 'joosy/joosy'
gem 'joosy-rails', github: 'joosy/joosy-rails'
gem 'jquery-rails'
gem 'rails', '4.0.2'
gem 'therubyracer'
